spring:
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:example@gmail.com}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  email:
    from: ${EMAIL_FROM:no-reply@gmail.com}
    subject-prefix: "[동아리 지원]"