spring:

  datasource:
    url: jdbc:h2:mem:~/team18
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
