name: Pull Request Discord Notification

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Send Discord notification on PR event
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: |
            **새로운 Pull Request가 생성되었습니다!** - **저장소:** `${{ github.repository }}`
            - **제목:** `${{ github.event.pull_request.title }}`
            - **작성자:** `${{ github.event.pull_request.user.login }}`
            - **링크:** ${{ github.event.pull_request.html_url }}
